// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_option.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUN2CmniNF4pZ8UZGp6q8dbffHJV247ww',
    appId: '1:1048012245072:web:3cb7df6061cfaa71cba955',
    messagingSenderId: '1048012245072',
    projectId: 'mfyptechnician-app',
    authDomain: 'mfyptechnician-app.firebaseapp.com',
    databaseURL: 'https://mfyptechnician-app-default-rtdb.firebaseio.com',
    storageBucket: 'mfyptechnician-app.appspot.com',
    measurementId: 'G-8RSNRZ9JZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX7qXPgTueXavLxcLp8VN9M89XnGdmo_U',
    appId: '1:1048012245072:android:f7d638043cb57209cba955',
    messagingSenderId: '1048012245072',
    projectId: 'mfyptechnician-app',
    databaseURL: 'https://mfyptechnician-app-default-rtdb.firebaseio.com',
    storageBucket: 'mfyptechnician-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDez8uNGAb9JMMHFoRToQOsdEQ8cAbFf8s',
    appId: '1:1048012245072:ios:3938e39f9d6827d2cba955',
    messagingSenderId: '1048012245072',
    projectId: 'mfyptechnician-app',
    databaseURL: 'https://mfyptechnician-app-default-rtdb.firebaseio.com',
    storageBucket: 'mfyptechnician-app.appspot.com',
    iosClientId: '1048012245072-85v0rd1uti11ph9rkltsn4jmlmfc68fa.apps.googleusercontent.com',
    iosBundleId: 'com.mfyp.cust',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDez8uNGAb9JMMHFoRToQOsdEQ8cAbFf8s',
    appId: '1:1048012245072:ios:3938e39f9d6827d2cba955',
    messagingSenderId: '1048012245072',
    projectId: 'mfyptechnician-app',
    databaseURL: 'https://mfyptechnician-app-default-rtdb.firebaseio.com',
    storageBucket: 'mfyptechnician-app.appspot.com',
    iosClientId: '1048012245072-85v0rd1uti11ph9rkltsn4jmlmfc68fa.apps.googleusercontent.com',
    iosBundleId: 'com.mfyp.cust',
  );
}
